# Generated by Django 2.1.3 on 2018-11-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='height',
            field=models.FloatField(max_length=6),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='weight',
            field=models.FloatField(max_length=5),
        ),
    ]
