# Generated by Django 2.1.3 on 2018-11-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0002_auto_20181126_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
