# Generated by Django 2.1.2 on 2018-10-31 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0002_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gener',
            field=models.CharField(choices=[('FE', 'Female'), ('MA', 'Male')], default='FE', max_length=2),
        ),
        migrations.AddField(
            model_name='statistics',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nutri.Patient'),
            preserve_default=False,
        ),
    ]
