# Generated by Django 2.1.3 on 2018-11-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0003_auto_20181126_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='harris',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='miffin',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='valencia',
            field=models.FloatField(max_length=10),
        ),
    ]
