# Generated by Django 2.1.3 on 2018-11-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri', '0004_auto_20181126_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='harris',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='miffin',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='valencia',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
